application: shorten
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /css
  static_dir: css

- url: /test.*
  script: gaeunit.py

- url: /.*
  script: shorten.app

libraries:
- name: jinja2
  version: latest